### ISSUE TITLE
USAS-ITDB contracts results page broken

### ISSUE THREAD

**Issue by jmendez35** [fedspendingtransparency/USASpending-Issue-Tracker#40]
On the IT Dashboard, contracts that matched with USASpending (based on the API described in https://github.com/fedspendingtransparency/USASpending-Issue-Tracker/issues/39) would display a link on the public contracts page to the specific contract on USAspending's website. This page now leads to a 404 error as well.

Contracts page on ITDB:
https://my.itdashboard.gov/investment/contracts/1099

Link to contract AG3142B090033:
http://usaspending.gov/customcode/contractsItdashboard.php?contractPIID=AG3142B090033&contractIDVPIID=GS35F5014H&contractAgencyID=3142&fundAgencyID=12&idvAgencyID=1205

**Comment by bsweger** [comment]
@jmendez35 Thank you for the report! I moved this information over to #39 so the team can track all errors related to the USAS-ITDB in one place (and so will close out this issue). Please let us know if you find anything else.

**Comment by jmendez35** [comment]
@bsweger This is an independent issue from #39. The other one relates to an API URL which returns an XML file result, while this issue refers to a search results page on USASpending which used to show the contracts related to the parameters entered. It was a page of the website, not a downloaded XML.

**Comment by bsweger** [comment]
@jmendez35 Thanks for checking back in. I had grouped the issues together because they were both impacting the functionality of the IT Dashboard and because both the API URL and the link to the contract information on USASpending were routed through the same "customcode" folder that no longer exists. 

Sounds like it might better to track these separately from your perspective, so I'll re-open this issue.
