### ISSUE TITLE
data download doesn't return results when end date is specified

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#45]
The download file isn't generated when you specify an end date parameter on the [data download screen](https://www.usaspending.gov/DownloadCenter/Pages/DataDownload.aspx). 

Entering the search parameters and clicking Submit take you to the _Summary Data_ screen. From there, clicking the _Generate File_ button brings up the _Generating File_ screen that stays there until you close it.

![image](https://cloud.githubusercontent.com/assets/540544/7184097/5a961ede-e429-11e4-8440-19f092d087ef.png)

I tried this on various combinations of Windows and OSX as well as IE, Safari, Crome, and Firefox. Here's a sample search parameter that resulted in the issue:
* award type = prime
* spending type = contracts
* agency = general services administration
* bureau = view all
* fiscal year = 2015
* recipient state/place of performance state = all
* obligation start date = 10/1/14
* obligation end date = 10/3/14

**Comment by askamp101** [comment]
Thank you so much.
Day totally got away from me. I’ll check on this in the morning.

**Comment by JohnEFreeman** [comment]
Once I get to "Generating file..." with a URL, I can copy the URL of the dialog box to, say, Excel.  Clicking gets a 404 error. 
Back at the dialog containing the "Generating file..." dialog, I expected to be able to close the dialog and click on the URL later, but that never worked.
So I left the "Generating file..." dialog open for many hours, and I finally got a "File generation is complete" message (or the equivalent).  I assumed that the file was there, so I clicked on the URL, which switched me to a new tab whose heading reads "Waiting for download.usaspending.gov", with an activity indicator. It's been like that for 4 hours or more.

**Comment by JohnEFreeman** [comment]
Failure to provide a FY data file occurs whether or not I provide an end date.

**Comment by bsweger** [comment]
@JohnEFreeman Thanks for reporting your experience. Can you provide a few more specifics about the search parameters you were using? For example, which agency/bureau, which fiscal year, and what type of file you requested (_e.g._, csv, xml).

Thanks again for taking the time to weigh in.

**Comment by JohnEFreeman** [comment]
More details on my Data Download requests:  I requested using these parameters:  Award type = prime, spending type = Contracts, Agency = All, Bureau = View All, Fiscal Year = 2015 ...2006 (each requested separately), Recipient State = All, Place of Performance State = All, Obligation Date, 
Start Date  = 10/01/[xxxx], End Date = 09/30/[yyyy] where xxxx = FY -1 and yyyy = FY, File Type = CSV or TSV (tried both).  I tried on Saturday, Sunday, and Monday, and once on Tuesday.  Feedback of number of records appeared correct for each request.  Sometimes I left off the End Date because of previously reported problems.   Initially, I assumed that, once I had the URL, I could close the dialog and wait and click on the URL to retrieve the file.  I did that successfully for FY2015 on Saturday, but have had no success since.
I have also let the dialog stay open until I received the message "File generation is complete" after which I clicked on the URL, and this opened a new Tab with the heading "Waiting for download.usaspending.gov"  with a spinning activity indicator.  That page was blank, and it never came back with a result.  (Never = at least 2 days).  I've tried this using Windows 7, Windows 8.1, and with IE 11.0.9600.11728 and later,  and Google Chrome version 42.0.2311.90 m.

**Comment by bsweger** [comment]
@JohnEFreeman thank you very much for providing the additional information. It sounds like there are two separate problems:

* getting an error message when downloading large volumes of data
* adding an end date to even a small search (< 50 records) causes an error message when downloading

I added the information you provided to #31, where others have also reported issues with large data downloads. We'll update that issue with more information as we get it.

Thanks again for taking the time to report.

**Comment by JohnEFreeman** [comment]
I have had one success, early on Saturday, and that included an end data of 9/30/2015 for FY2015.  All of my other attempts failed with or without an end date.  I'm not sure what this says about the problem.  Have other people had success without an end date since Saturday morning 20150418?

**Comment by bsweger** [comment]
@JohnEFreeman I can't speak to exact timing, but #31, the issue where we've been tracking download problems, was re-opened on Monday 4/20. It's also interesting that you were able to download with an end date on Saturday--thank you for letting us know.

**Comment by USAspendingalice** [comment]
@JohnEFreeman We can no longer replicate this issue.  Are you still having problems with the download?

**Comment by USAspendingalice** [comment]
This issue has been resolved.
