### ISSUE TITLE
Advanced Search - there should be a global keyword field searching all FPDS data fields.  Search should support full boolean commands

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#58]

**Comment by bsweger** [comment]
@betterdataneeded Thanks for all of the requests and sorry for responding to everything last week. The keyword search is being expanded to include the award description field (see #9) and a few others. That work does not represent the ability to search all FPDS fields, so we'll keep this issue open as an enhancement request.

Also, I'll double-check on whether or not the keyword searches will incorporate boolean commands.

**Comment by USAspendingalice** [comment]
@betterdataneeded We're closing this issue because the keyword now supports the Boolean search. You can find more information on the recent improvements to the site at https://www.usaspending.gov/about/Pages/What's-New.aspx.  As to the expanded FPDS fields, for now this is all we're offering. Please feel free to come back if you have other issues.
