### ISSUE TITLE
Sub-Award download not working, CSV

### ISSUE THREAD

**Issue by Umer08** [fedspendingtransparency/USASpending-Issue-Tracker#62]
Upon attempting to download sub-award data from the Download Center, I am receiving the following error: "Error generating file. Please retry." This is a significant issue. I have opened up tickets previously for the XML downloads not working properly for sub-award data. However, it seems like the CSV download is now broken as well. Please investigate!

![image](https://cloud.githubusercontent.com/assets/10675575/7458688/5d93482a-f264-11e4-85ef-db13182468a3.png)

**Comment by bsweger** [comment]
@Umer08 Thanks for posting your error. There is a known issue (being tracked in #31) with large data download requests causing this error message. I'm closing out this issue because it's a duplicate, but wanted you to know that the fix is in progress, and updates will be posted over on the [original issue thread](https://github.com/fedspendingtransparency/USASpending-Issue-Tracker/issues/31).

I know you've been having a lot of trouble with the site, and I want to both apologize and thank you for your patience and willingness to continue reporting issues.
